# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Interface > Pull request

on:
  pull_request:
    paths:
      - "interface/**"

jobs:
  test:
    uses: ./.github/workflows/interface_test.yml
    secrets: inherit
