# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Interface > Push to Main

on:
  push:
    branches:
      - main

concurrency: deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_ID: app_e77e446e-754a-433d-8f8f-fe339d699a75

jobs:
  test_interface:
    uses: ./.github/workflows/interface_test.yml
    secrets: inherit

  deploy_interface:
    uses: ./.github/workflows/interface_deploy.yml
    needs: test_interface
    secrets: inherit
