# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Pull request

on:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  test_interface:
    uses: ./.github/workflows/test_interface.yml
    secrets: inherit
